apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: nginx
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: devt-lx-quay.devtest.local:8443/ocp4/nginx:latest
      from:
        kind: DockerImage
        name: devt-lx-quay.devtest.local:8443/ocp4/nginx:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: webserver:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: buildapp
      git:
        uri: https://github.com/ebeaudoi/webserver.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:latest
      type: Docker
    triggers:
    - github:
        secret: U5CWo7I7la5ny2s64Lls
      type: GitHub
    - generic:
        secret: MInCc-lONj-KDw3OYKZr
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"webserver:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"webserver\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: webserver
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: webserver
      spec:
        containers:
        - image: ' '
          name: webserver
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webserver
      app.kubernetes.io/component: webserver
      app.kubernetes.io/instance: webserver
    name: webserver
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: webserver
  status:
    loadBalancer: {}
kind: List
metadata: {}
