#FROM quay.io/ebeaudoi/nginx-120:latest
#FROM registry.redhat.io/rhel8/nginx-114
#FROM nginx:latest
FROM quay.io/ebeaudoi/nginx:latest

COPY ./index.html /usr/share/nginx/html/index.html

EXPOSE 8080
 
