apiVersion: v1
kind: Service
metadata:
  name: ebdn-nginx-webserver-service
  namespace: testproject
spec:
  selector:
    app: ebdn-nginx-webserver
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
